Publish CRDA task into Tekton Hub
jparsai/catalog pull request #1
Opened 2021-03-18 05:54 UTC by jparsai

2021-03-29 06:36 UTC, prashbnair requested changes

2021-03-29 06:36 UTC, prashbnair commented on task/crda-analysis/0.1/crda-analysis.yaml
> +    - name: work-dir
Can we not take a full path to the manifest instead of adding a new parameter?

2021-03-29 06:45 UTC, prashbnair commented on task/crda-analysis/0.1/crda-analysis.yaml
> +        sh /crda_dir/crda.sh \
Is there a script named crda.sh

2021-03-29 06:47 UTC, jparsai commented on task/crda-analysis/0.1/README.md
> +- **work-dir**: Path of directory in workspace, which contains packages installation directory (`site-pkg-directory`) and manifest file (`manifest-file-name`), during task execution generated report
Because we don't know where is manifest file placed by previous task. we are assuming that manifest file is inside working directory (i.e. where project is cloned) and in the same directory we need to save the report as well.

2021-03-29 06:47 UTC, jparsai commented on task/crda-analysis/0.1/crda-analysis.yaml
> +    - name: work-dir
Yes, we can take full path of manifest, then we dont need to ask for working directory.
Only issue will be that we wont know where user wants to save the report, by default we can save in PVC home directory, but if there is another file with same name it will overwrite.

2021-03-29 06:48 UTC, jparsai commented on task/crda-analysis/0.1/crda-analysis.yaml
> +        sh /crda_dir/crda.sh \
Yes, I need to add that in our internal repo used for Image building. 
https://github.com/fabric8-analytics/crda-images

2021-03-29 06:52 UTC, jparsai commented on task/crda-analysis/0.1/crda-analysis.yaml
> +        sh /crda_dir/crda.sh \
So next time if we need to change anything or introduce new ecosystem we no need to change anything in Tekton Task, instead we can upload new image with and it will reflect in task.

2021-03-29 07:02 UTC, jparsai commented on task/crda-analysis/0.1/README.md
> +- **work-dir**: Path of directory in workspace, which contains packages installation directory (`site-pkg-directory`) and manifest file (`manifest-file-name`), during task execution generated report
I think that will create confusion, instead of assuming that pks-installation-directory and manifest file are inside working directory, I should ask absolute path itself to pkg-installation-directory and manifest file.

2021-03-31 10:17 UTC, prashbnair requested changes

2021-03-31 10:17 UTC, prashbnair commented on task/crda-analysis/0.1/README.md
> +#### 1. Workspace
```suggestion
#### 1. Creation of Workspace
```

2021-04-05 06:15 UTC, merged